### ISSUE TITLE
If Variant inventory count = 0, currently allows user to select and add variant to cart

### ISSUE THREAD

**Issue by Sapphire-Creative** [sapphire-creative-llc/ragen#2]
When a variant is out of stock, the variant option should be either: grayed out and unelectable OR selectable but the add to cart button should be deselected with a line of text saying "Out of stock"

<img width="579" alt="image" src="https://user-images.githubusercontent.com/43766557/47273155-cba40900-d55d-11e8-854f-7419101e7ebf.png">

**Comment by dhunninghake** [comment]
Fix in this commit! https://github.com/sapphire-creative-llc/ragen/commit/d5b154a41210108d7173817e027e818584fdef6f
