### ISSUE TITLE
Smaller screen size: product page issues

### ISSUE THREAD

**Issue by Sapphire-Creative** [sapphire-creative-llc/ragen#3]
When horizontally collapsing the size of the screen, the product page encounters styling issues:
<img width="885" alt="image" src="https://user-images.githubusercontent.com/43766557/47273174-1de52a00-d55e-11e8-90ea-5589571f0b82.png">

**Comment by dhunninghake** [comment]
Fixed in this commit! https://github.com/sapphire-creative-llc/ragen/commit/1e42348936d1533411b3bf405ceefc92e182c16a
