### ISSUE TITLE
Mobile: Add to Jewel Bag button style

### ISSUE THREAD

**Issue by Sapphire-Creative** [sapphire-creative-llc/ragen#4]
![img_2082](https://user-images.githubusercontent.com/43766557/47273188-7f0cfd80-d55e-11e8-8c2b-5e72948a2c7a.PNG)

**Comment by dhunninghake** [comment]
Fixed in this commit! https://github.com/sapphire-creative-llc/ragen/commit/1e42348936d1533411b3bf405ceefc92e182c16a
